# ================================
# Docker Compose for Hadoop HA Cluster
# ================================
version: '3.8'

services:
  master1:
    build:
      context: .
    hostname: master1
    container_name: master1
    ports:
      - "8888:8088"
      - "9878:9870"
    networks:
      - hadoopnet
    volumes:
      - zk1-data:/usr/local/zookeeper
      - jk1:/usr/local/hadoop/journal
      - hdfs-nn1:/usr/local/hadoop/hdfs/namenode

  master2:
    build:
      context: .
    hostname: master2
    container_name: master2
    ports:
      - "8788:8088"
      - "9877:9870"
    networks:
      - hadoopnet
    volumes:
      - zk2-data:/usr/local/zookeeper
      - jk2:/usr/local/hadoop/journal
      - hdfs-nn2:/usr/local/hadoop/hdfs/namenode

  master3:
    build:
      context: .
    hostname: master3
    container_name: master3
    ports:
      - "8688:8088"
      - "9876:9870"
    networks:
      - hadoopnet
    volumes:
      - zk3-data:/usr/local/zookeeper
      - jk3:/usr/local/hadoop/journal
      - hdfs-nn3:/usr/local/hadoop/hdfs/namenode

  worker:
    build:
      context: .
    hostname: worker
    container_name: worker
    networks:
      - hadoopnet
    volumes:
      - hdfs-dn1:/usr/local/hadoop/hdfs/datanode

networks:
  hadoopnet:
    driver: bridge

volumes:
  zk1-data:
  jk1:
  zk2-data:
  jk2:
  zk3-data:
  jk3:
  hdfs-nn1:
  hdfs-nn2:
  hdfs-nn3:
  hdfs-dn1:




