services:
  master1:
    build:
      context: .
      target: hadoop-base
    image: hadoop-base
    hostname: master1
    container_name: master1
    ports:
      - "8888:8088"
      - "9878:9870"
    networks:
      - hadoopnet
    volumes:
      - zk1-data:/usr/local/zookeeper
      - jk1:/usr/local/hadoop/journal
      - hdfs-nn1:/usr/local/hadoop/hdfs/namenode
    healthcheck:
      test: ["CMD-SHELL", "hdfs haadmin -checkHealth nn1"]
      interval: 10s
      timeout: 5s
      retries: 5

  master2:
    image: hadoop-base
    hostname: master2
    container_name: master2
    ports:
      - "8788:8088"
      - "9877:9870"
    networks:
      - hadoopnet
    volumes:
      - zk2-data:/usr/local/zookeeper
      - jk2:/usr/local/hadoop/journal
      - hdfs-nn2:/usr/local/hadoop/hdfs/namenode
    healthcheck:
      test: ["CMD-SHELL", "hdfs haadmin -checkHealth nn2"]
      interval: 10s
      timeout: 5s
      retries: 5

  master3:
    image: hadoop-base
    hostname: master3
    container_name: master3
    ports:
      - "8688:8088"
      - "9876:9870"
    networks:
      - hadoopnet
    volumes:
      - zk3-data:/usr/local/zookeeper
      - jk3:/usr/local/hadoop/journal
      - hdfs-nn3:/usr/local/hadoop/hdfs/namenode
    healthcheck:
      test: ["CMD-SHELL", "hdfs haadmin -checkHealth nn3"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    image: hadoop-base
    hostname: worker
    container_name: worker
    networks:
      - hadoopnet
    volumes:
      - hdfs-dn1:/usr/local/hadoop/hdfs/datanode
    depends_on:
      master1:
        condition: service_healthy
      master2:
        condition: service_healthy
      master3:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f DataNode && pgrep -f NodeManager"]
      interval: 10s
      timeout: 5s
      retries: 5

  hive-postgres:
    image: postgres:13
    hostname: hive-postgres
    container_name: hive-postgres
    environment:
      POSTGRES_USER: hiveuser
      POSTGRES_PASSWORD: hivepassword
      POSTGRES_DB: metastore
    networks:
      - hadoopnet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hiveuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  hive-metastore:
    build: .
    image: hive-base
    hostname: hive-metastore
    container_name: hive-metastore
    networks:
      - hadoopnet
    # healthcheck:
    #   test: ["CMD-SHELL", "nc -z localhost 9083"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    depends_on:
      hive-postgres:
        condition: service_healthy
      master1:
        condition: service_healthy

  hive-server2:
    build: .
    image: hive-base
    hostname: hive-server2
    container_name: hive-server2
    ports:
      - "10000:10000"
    networks:
      - hadoopnet
    depends_on:
      # hive-metastore:
      #   condition: service_healthy
      worker:
        condition: service_healthy

networks:
  hadoopnet:
    driver: bridge

volumes:
  zk1-data:
  jk1:
  zk2-data:
  jk2:
  zk3-data:
  jk3:
  hdfs-nn1:
  hdfs-nn2:
  hdfs-nn3:
  hdfs-dn1:
  postgres-data: